import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useSession } from "next-auth/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session, status } = useSession();
  let dynamicContent = <h1>Not signed in</h1>;
  if (status === "authenticated") {
    dynamicContent = (
      <h1>
        Signed in as {session.user.email} <br />
      </h1>
    );
  }
  return (
    <>
      <Head>
        <title>PlantDex (TASHI in dev)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div>Hello</div>
    </>
  );
}
